// Users endpoints
###
GET http://localhost:3306/users
Content-Type: application/json

###
GET http://localhost:3306/users/user/97eb48b8-a657-4423-927e-8b4c9fd88376
Content-Type: application/json

###
POST http://localhost:3306/users
Content-Type: application/json

{
    "fullName": "maria",
    "email": "maria@gmail.com",
    "password": "12345678"
}

// Posts endpoints
###
GET http://localhost:3306/posts
Content-Type: application/json

###
GET http://localhost:3306/posts/post/:id
Content-Type: application/json

###
POST http://localhost:3306/posts
Content-Type: application/json

{
    "photo": "https://i.pinimg.com/originals/e4/34/2a/e4342a4e0e968344b75cf50cf1936c09.jpg",
    "description": "Wolf.",
    "type": "NORMAL",
    "authorId": "18672235-4051-470b-91c6-58d83f28762f"
}

// Friendships endpoints
###
GET http://localhost:3306/friendships
Content-Type: application/json

###
POST http://localhost:3306/friendships/75a9b1ca-223a-4cc0-8de6-8e47991c75d4
Content-Type: application/json

{
    "friendId": "8199b2cb-8090-47bd-808b-0903162e2187"
}

###
DELETE http://localhost:3306/friendships/97eb48b8-a657-4423-927e-8b4c9fd88376
Content-Type: application/json

{
    "friendId": "8199b2cb-8090-47bd-808b-0903162e2187"
}

